## YAML Template.
version: '2'
services:
    app-spring-docker-srv:
        image: fabgue/app-spring-docker
        external_links:
            - db:postgres
        ports:
            - 8080:8080
            - 8000:8000
    db:
        image: postgres
        environment:
            - POSTGRES_DB=demo
            - POSTGRES_PASSWORD=mgrdev1P
            - POSTGRES_USER=developer
        ports:
            - 5432:5432